sudo: required

env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_FILE_ASPNET_BUILD=$CACHE_DIR/aspnet-build.tar.gz
    - CACHE_FILE_ASPNETCORE=$CACHE_DIR/aspnetcore.tar.gz
    - DOCKER_COMPOSE_VERSION=1.11.2

cache:
  directories:
  - $CACHE_DIR

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - if [ -f ${CACHE_FILE_ASPNET_BUILD} ]; then gunzip -c ${CACHE_FILE_ASPNET_BUILD} | docker load; fi
  - if [ -f ${CACHE_FILE_ASPNETCORE} ]; then gunzip -c ${CACHE_FILE_ASPNETCORE} | docker load; fi
  - if [ ! -f ${CACHE_FILE_ASPNET_BUILD} ]; then docker pull microsoft/aspnetcore-build:1.0-1.1; docker save microsoft/aspnetcore-build:1.0-1.1 | gzip > ${CACHE_FILE_ASPNET_BUILD}; fi
  - if [ ! -f ${CACHE_FILE_ASPNETCORE} ]; then docker pull microsoft/aspnetcore:1.1; docker save microsoft/aspnetcore:1.1 | gzip > ${CACHE_FILE_ASPNETCORE}; fi

script:
  - docker-compose -f docker-compose.ci.build.yml run ci-build
  - docker-compose -f docker-compose.yml -f docker-compose.vs.release.yml build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag biowareru/bioengine-resizr:latest biowareru/bioengine-resizr:1.0-$TRAVIS_BUILD_NUMBER;
    docker push biowareru/bioengine-resizr;
    docker tag biowareru/bioengine-site:latest biowareru/bioengine-site:1.0-$TRAVIS_BUILD_NUMBER;
    docker push biowareru/bioengine-site;
    docker tag biowareru/bioengine-api:latest biowareru/bioengine-api:1.0-$TRAVIS_BUILD_NUMBER;
    docker push biowareru/bioengine-api;
    fi