pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      projects: '**/*.csproj'
      feedsToUse: 'select'
      verbosityRestore: 'minimal'
      vstsFeed: 'BioEngine'
      
  - task: DotNetCoreCLI@2
    inputs:
      command: custom
      custom: publish
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      arguments: '--no-restore -c Release --output ./.docker/publish'
      projects: 'src/Site/BioEngine.Site.csproj;src/API/BioEngine.API.csproj'

  - script: docker build -f src/Site/.docker/Dockerfile -t biowareru/bioengine-site:1.0-$(build.buildId) -t biowareru/bioengine-site:latest src/Site/.docker
    displayName: 'build site image'
  - script: docker build -f src/API/.docker/Dockerfile -t biowareru/bioengine-api:1.0-$(build.buildId) -t biowareru/bioengine-api:latest src/API/.docker
    displayName: 'build api image'
  - script: docker login -u $(dockerId) -p $(dockerPswd)
    displayName: 'login to docker hub'
  - script: |
      docker push biowareru/bioengine-site:1.0-$(build.buildId)
      docker push biowareru/bioengine-site:latest
    displayName: 'push site image'
  - script: |
      docker push biowareru/bioengine-api:1.0-$(build.buildId)
      docker push biowareru/bioengine-api:latest
    displayName: 'push api image'
