pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: dotnet restore
  displayName: 'restore'
- script: dotnet publish src/Site/BioEngine.Site.csproj -c Release --output ./.docker/publish
  displayName: 'publish site'
- script: dotnet publish src/API/BioEngine.API.csproj -c Release --output ./.docker/publish
  displayName: 'publish api'
- script: docker build -f src/Site/.docker/Dockerfile -t biowareru/bioengine-site:1.0-$(build.buildId) src/Site/.docker
  displayName: 'build site image'
- script: docker build -f src/API/.docker/Dockerfile -t biowareru/bioengine-api:1.0-$(build.buildId) src/API/.docker
  displayName: 'build api image'
- script: docker login -u $(dockerId) -p $(dockerPswd)
  displayName: 'login to docker hub'
- script: docker push biowareru/bioengine-site:1.0-$(build.buildId)
  displayName: 'push site image'
- script: docker push biowareru/bioengine-api:1.0-$(build.buildId)
  displayName: 'push api image'