version: '2'

services:
  resizr:
    image: resizr
    build:
      context: ./src/Resizr
      dockerfile: Dockerfile
  mysql:
    image: mariadb:latest
  elasticsearch:
    image: elasticsearch:alpine