//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioEngine.Site.Resources.Views.Shared.News {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Show {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Show() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Site.Resources.Views.Shared.News.Show", typeof(Show).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} comments.
        /// </summary>
        public static string Comments_Few {
            get {
                return ResourceManager.GetString("Comments_Few", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} comments.
        /// </summary>
        public static string Comments_Many {
            get {
                return ResourceManager.GetString("Comments_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} comment.
        /// </summary>
        public static string Comments_One {
            get {
                return ResourceManager.GetString("Comments_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} comments.
        /// </summary>
        public static string Comments_Other {
            get {
                return ResourceManager.GetString("Comments_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Discuss on forum.
        /// </summary>
        public static string Comments_Zero {
            get {
                return ResourceManager.GetString("Comments_Zero", resourceCulture);
            }
        }
    }
}
